# Generated by Django 3.1.2 on 2020-10-18 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('precio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio del producto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción del producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/%d/%m/%Y', verbose_name='Imagen del producto')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
